name: vietnam_map_01
description: "VietNam Map Checkin Flutter app"
publish_to: 'none'

version: 260919.1.0+26091901

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  http: ^1.2.2
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  file_selector: ^1.1.0
  image_picker: ^1.1.2
  path: ^1.9.1
  archive: ^4.3.0
  crypto: ^3.0.7
  cryptography: ^2.9.0
  flutter_secure_storage: ^11.2.0
  geolocator: ^14.0.3
  image: ^4.10.1
  path_provider: ^2.1.6
  share_plus: ^13.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/App_VietNamMap_Logo_no_background.png
    - assets/vietnam-provinces.geojson
