#!/usr/bin/env python3
"""Decode the supplied QR images, verify TFT-sized replacements, print a header.

Dependencies (host only): qrcode, pillow, zxing-cpp.
Usage: python generate_qr_assets.py BANK_IMAGE PROFILE_IMAGE
The generated header is checked into include/qr_assets.h; firmware has no QR
encoder dependency. Payloads, including the original profile redirect, stay exact.
"""

import argparse
import sys

import qrcode
import zxingcpp
from PIL import Image


def generate(name, path):
    decoded = zxingcpp.read_barcodes(Image.open(path))
    assert len(decoded) == 1, f"{name}: expected exactly one readable QR"
    payload = decoded[0].text
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=0)
    qr.add_data(payload)
    qr.make(fit=True)
    matrix = qr.get_matrix()
    size = len(matrix)
    scale = 128 // (size + 8)
    assert scale >= 2, f"{name}: too dense for a reliably sized TFT QR"
    side = (size + 8) * scale
    # Reproduce the firmware's exact integer pixels and four-module quiet zone.
    raster = Image.new("L", (128, 160), 255)
    left = (128 - side) // 2 + 4 * scale
    top = 17 + (124 - side) // 2 + 4 * scale
    assert side <= 124
    for y, row in enumerate(matrix):
        for x, black in enumerate(row):
            if black:
                raster.paste(0, (left + x * scale, top + y * scale,
                                 left + (x + 1) * scale, top + (y + 1) * scale))
    result = zxingcpp.read_barcodes(raster)
    assert len(result) == 1 and result[0].text == payload, f"{name}: TFT round-trip failed"
    # Store rows padded to whole bytes, as expected by drawQrCode().
    packed = []
    for row in matrix:
        for offset in range(0, size, 8):
            packed.append(sum(0x80 >> bit for bit in range(8)
                              if offset + bit < size and row[offset + bit]))
    stride = (size + 7) // 8
    assert all(bool(packed[y * stride + x // 8] & (0x80 >> (x % 8))) == bool(matrix[y][x])
               for y in range(size) for x in range(size)), f"{name}: packed bitmap differs"
    print(f"constexpr uint8_t {name}_QR_SIZE = {size};")
    print(f"const uint8_t {name}_QR_BITS[] PROGMEM = {{")
    for offset in range(0, len(packed), 12):
        print("    " + ", ".join(f"0x{byte:02x}" for byte in packed[offset:offset + 12]) + ",")
    print("};\n")
    print(f"{name}: original and TFT QR match; {size} modules, {scale}px/module, "
          f"{side}px including quiet zone", file=sys.stderr)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("bank")
    parser.add_argument("profile")
    args = parser.parse_args()
    print("// Generated by tools/generate_qr_assets.py. Do not resize with filtering.\n"
          "#pragma once\n#include <Arduino.h>\n")
    generate("BANK", args.bank)
    generate("PROFILE", args.profile)
